site_name: Mojo Game of Life
docs_dir: docs
site_dir: site

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue gray
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Repository
repo_name: mojo-game-of-life
repo_url: https://github.com/yourusername/mojo-game-of-life
edit_uri: edit/main/docs/

# Copyright
copyright: "Copyright &copy; 2025 Your Name"

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Basic Usage: guide/usage.md
    - Configuration: guide/configuration.md
    - Controls: guide/controls.md
  - API Reference:
    - Life: api/life.md
    - Grid: api/grid.md
  - Development:
    - Building: development/building.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - About:
    - License: about/license.md
    - Changelog: about/changelog.md

# Plugins
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

# Extra
extra:
  analytics:
    provider: google
    property: YOUR-GA-PROPERTY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/mojo-game-of-life
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername

# Build
strict: true
use_directory_urls: true
